name: Delete All Packages

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Delete Previous Packages
        uses: actions/delete-package-versions@v1
        with:
          package-name: 'uk.co.devworx.elt-with-objects'
