name: Java LTS Build on Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test Against LTS Java Versions
        java: [ 8, 11 ]
        #java: [ 8, 11, 17 ] - Waiting for Spark 3.3.0 - before we can do 17

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java Version
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Maven Modules
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-devworx-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-devworx-maven-

      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password

